table_name: products_silver

source:
  path: /Volumes/pei/bronze/product/
  format: parquet

target:
  path: /Volumes/pei/silver/products/
  format: delta
  mode: overwrite

schema:
  - name: product_id
    source_name: "Product ID"
    type: string
    nullable: false

  - name: category
    source_name: "Category"
    type: string

  - name: subcategory
    source_name: "Sub-Category"
    type: string

  - name: product_name
    source_name: "Product Name"
    type: string

  - name: state
    source_name: "State"
    type: string

  - name: product_price
    source_name: "Price per product"
    type: string

  - name: ingestion_timestamp
    source_name: "ingestion_timestamp"
    type: timestamp

  - name: source_file
    source_name: "source_file"
    type: string


columns:
  select:
    - product_id
    - category
    - subcategory
    - product_price
    - ingestion_timestamp


deduplication:
  keys: [product_id]
  order_by: ingestion_timestamp
  strategy: latest

quality_checks:
  - column: product_id
    rule: not_null

  # - column: price
  #   rule: ">= 0"